credentials:
  usernames:
    echrappah:
      email: emmanuel.chrappah@azubiafrica.org
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Emmanuel Chrappah
      password: emma # Will be hashed automatically
    ikwatei:
      email: isaac@gmail.com
      failed_login_attempts: 0 
      logged_in: False 
      name: Isaac Kwatei
      password: isaac     
    azubi:
      email: azubi@azubi.org
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: azubiafrica
      password: azubi # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - emmanuel.chrappah@azubiafrica.org